server.port: 8084

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: info
    com.example: debug

event-consumer:
  topics:
    simple-one: simple-one
    simple-two: simple-two
    logical-one: logical-one
    logical-two: logical-two
  properties:
    group.id: spring-group-1
    bootstrap.servers: kafka.local:9092
    schema.registry.url: http://kafka-tools.local:8081
    key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
    avro.use.logical.type.converters: true

dlt-producer:
  properties:
    bootstrap.servers: kafka.local:9092
    schema.registry.url: http://kafka-tools.local:8081
    key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
