server.port: 8082

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: info
    com.example: debug

kafka:
  bootstrap.servers: localhost:9092
  schema.registry.url: http://localhost:8081

event-producer:
  topics:
    simple-one: simple-one
    simple-two: simple-two
    logical-one: logical-one
    logical-two: logical-two
  properties:
    bootstrap.servers: ${kafka.bootstrap.servers}
    schema.registry.url: ${kafka.schema.registry.url}
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    avro.use.logical.type.converters: true
    auto.register.schemas: false
    use.latest.version: true

reflected-event-producer:
  topics:
    reflected-one: reflected-one
    reflected-two: reflected-two
  properties:
    bootstrap.servers: ${kafka.bootstrap.servers}
    schema.registry.url: ${kafka.schema.registry.url}
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: io.confluent.kafka.streams.serdes.avro.ReflectionAvroSerializer
    avro.reflection.allow.null: true
    auto.register.schemas: true
    use.latest.version: true
