CREATE ROLE kafkaconnect WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	REPLICATION
	CONNECTION LIMIT -1
    PASSWORD 'kafkaconnect123';

CREATE DATABASE kafkaconnect
    WITH OWNER=kafkaconnect ENCODING = 'UTF8' CONNECTION LIMIT = -1;